name: Deploy to Firebase
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - run: cd functions && npm ci
      - run: cd functions && npm run build
      
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: firebase deploy --token "\${{ secrets.FIREBASE_TOKEN }}" --project "arex-ltd-42154393-a701b-fce9f"
